baseurl = "https://www.omgcommunity.network/"
title = "OMG"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "Network/"
  url = "omgnetwork/"

  [[params.navlinks]]
  name = "omgpool/"
  url = "omgpool/"

  [[params.navlinks]]
  name = "Deposits/"
  url = "deposit/"

  [[params.navlinks]]
  name = "Rankings/"
  url = "rankings/"

  [[params.navlinks]]
  name = "Memes/"
  url = "memes/"